Use the value prop from v-model
drewjbartlett/vue-switches pull request #7
Opened 2017-05-24 23:00 UTC by francois2metz

See #6 

The selected prop is not really needed.

2017-05-30 16:23 UTC, drewjbartlett commented
I ran this on my local machine and I've noticed it now takes 2 initial clicks before the switch is changed. I'm assuming this may be potentially because of changing from @click to @input but I may be wrong. I don't have the time to dig into this at the moment but I really appreciate the help on this! I will definitely accept this PR once we get that issue figured out :)

2017-05-30 18:15 UTC, francois2metz commented
The initial PR included the change to `@input`, but it was a mistake. I since fixed it.

I'll look at it.

2017-05-31 15:18 UTC, francois2metz commented
I cannot reproduce the issue. Do you have a testcase?

2017-06-18 19:03 UTC, korzhyk commented
Use `@change` instead of `@click`.

2017-06-18 19:09 UTC, korzhyk requested changes
Use `@change` instead of `@click`.

2017-06-18 19:09 UTC, korzhyk commented on switches.vue
> +        <input type="checkbox" :disabled="disabled" @click="trigger">
Need to add `:checked="value"` for proper rendering actual state of checkbox.

2017-06-18 21:26 UTC, francois2metz commented
Thanks for your review @korzhyk. I updated the code.

2017-06-19 22:22 UTC, merged

2017-06-19 22:23 UTC, drewjbartlett commented
That fixed it! Thanks!

2019-05-02 10:07 UTC, kalashnikovisme commented
I have to use `@input` in such case.
`@click` and `@change` don't work unfortunately :(

Version: 2.0.1

2019-05-02 10:07 UTC, kalashnikovisme commented
What may be do I wrong?